const { _electron: electron } = require('@playwright/test');

// Customer personas (generated by the persona agents)
const PERSONAS = [
  { familyName:"Dela Cruz", barangay:"Barangay Holy Spirit", phone:"0917 542 8836", email:"marvin.delacruz28@gmail.com",
    members:[
      {first:"Marvin",middle:"Reyes",last:"Dela Cruz",birth:"1994-03-12"},
      {first:"Jhoanna",middle:"Lim",last:"Dela Cruz",birth:"1996-08-25"},
      {first:"Mateo",middle:"Lim",last:"Dela Cruz",birth:"2026-04-30"},
    ]},
  { familyName:"Bautista", barangay:"Barangay Poblacion", phone:"0917 532 8841", email:"jmdelacruz.rg@gmail.com",
    members:[
      {first:"Jericho",middle:"Mercado",last:"Dela Cruz",birth:"1995-03-14"},
      {first:"Maria Angelica",middle:"Reyes",last:"Bautista",birth:"1997-08-22"},
    ]},
];

async function addFamily(win, fam) {
  await win.getByRole('button', { name: /Add Family/i }).first().click();
  await win.waitForTimeout(500);
  await win.getByPlaceholder('e.g., Dela Cruz').fill(fam.familyName);
  await win.getByPlaceholder('09XX XXX XXXX').fill(fam.phone);
  const emailField = win.getByPlaceholder('family@email.com');
  if (await emailField.count()) await emailField.fill(fam.email);
  // members: first row exists; add rows for the rest
  for (let i = 0; i < fam.members.length; i++) {
    if (i > 0) { await win.getByRole('button', { name: /Add Member/i }).click(); await win.waitForTimeout(250); }
    const m = fam.members[i];
    await win.getByPlaceholder('First Name').nth(i).fill(m.first);
    const mid = win.getByPlaceholder('Middle Name').nth(i); if (await mid.count() > i) await mid.fill(m.middle).catch(()=>{});
    await win.getByPlaceholder('Last Name').nth(i).fill(m.last);
  }
  await win.getByRole('button', { name: /Save Family/i }).click();
  await win.waitForTimeout(900);
  const stillOpen = await win.getByRole('button', { name: /Save Family/i }).count() > 0;
  return !stillOpen; // saved if modal closed
}

(async () => {
  // Write to the REAL app data dir so this becomes usable seed data
  const app = await electron.launch({ args: ['.', '--no-sandbox'] });
  const win = await app.firstWindow();
  await win.waitForLoadState('domcontentloaded');
  await win.evaluate(() => {
    localStorage.setItem('churchos_setup_complete','true');
    localStorage.setItem('churchos_user', JSON.stringify({username:'parish.secretary',role:'secretary',roleLabel:'Secretary',loginAt:new Date().toISOString()}));
  });
  await win.evaluate(()=>{ window.location.hash='#/directory'; }); await win.reload(); await win.waitForTimeout(1500);

  let saved = 0;
  for (const fam of PERSONAS) {
    try { if (await addFamily(win, fam)) { saved++; console.log('SECRETARY entered family:', fam.familyName); } else console.log('BLOCKED:', fam.familyName); }
    catch (e) { console.log('ERROR on', fam.familyName, ':', e.message); }
  }

  // Verify in SQLite via real IPC
  const dump = await win.evaluate(async () => await window.churchos.db.getAll());
  const fk = Object.keys(dump).find(k => k.endsWith('_families'));
  const fams = fk ? JSON.parse(dump[fk]) : [];
  const entered = fams.filter(f => ['Dela Cruz','Bautista'].includes(f.familyName) && f.members && f.members.length);
  console.log('SQLITE_FAMILY_COUNT:', fams.length);
  console.log('PERSONA_FAMILIES_WITH_MEMBERS:', entered.map(f=>`${f.familyName}(${f.members.length})`).join(', '));
  await app.close();

  // Restart -> confirm the seed data persisted
  const app2 = await electron.launch({ args: ['.', '--no-sandbox'] });
  const win2 = await app2.firstWindow(); await win2.waitForLoadState('domcontentloaded');
  await win2.waitForTimeout(800);
  const dump2 = await win2.evaluate(async () => await window.churchos.db.getAll());
  const fk2 = Object.keys(dump2).find(k => k.endsWith('_families'));
  const fams2 = fk2 ? JSON.parse(dump2[fk2]) : [];
  console.log('AFTER_RESTART_FAMILY_COUNT:', fams2.length);
  await app2.close();
  console.log('SEED_DONE saved=' + saved);
})().catch(e => { console.log('SEED_FAIL:', e.message); process.exit(1); });
